#!/usr/bin/env python3
"""claude-review - Claude Code PR Review Agent"""
import argparse, json, os, re, sys, urllib.request
from dataclasses import dataclass, field

@dataclass
class PRInfo:
    owner: str = ""
    repo: str = ""
    number: int = 0
    title: str = ""
    description: str = ""
    author: str = ""
    base_branch: str = ""
    head_branch: str = ""
    changed_files: int = 0
    additions: int = 0
    deletions: int = 0
    diff: str = ""
    commit_messages: list = field(default_factory=list)

def parse_pr_url(url):
    m = re.search(r"github\.com/([^/]+)/([^/]+)/pull/(\d+)", url)
    if not m: raise ValueError("Invalid PR URL")
    return m.group(1), m.group(2), int(m.group(3))

def gh_api(path, accept="application/vnd.github.v3+json"):
    token = os.environ.get("GITHUB_TOKEN", "")
    req = urllib.request.Request(
        "https://api.github.com" + path,
        headers={"User-Agent": "claude-review", "Accept": accept}
    )
    if token:
        req.add_header("Authorization", "Bearer " + token)
    with urllib.request.urlopen(req, timeout=30) as r:
        data = r.read()
        ct = r.headers.get("Content-Type", "")
        return json.loads(data) if ct.startswith("application/json") else data

def fetch_pr(owner, repo, num):
    info = PRInfo(owner=owner, repo=repo, number=num)
    pr = gh_api(f"/repos/{owner}/{repo}/pulls/{num}")
    info.title = pr.get("title", "")
    info.description = pr.get("body", "") or ""
    info.author = pr.get("user", {}).get("login", "")
    info.changed_files = pr.get("changed_files", 0)
    info.additions = pr.get("additions", 0)
    info.deletions = pr.get("deletions", 0)
    commits = gh_api(f"/repos/{owner}/{repo}/pulls/{num}/commits")
    for c in commits:
        msg = c.get("commit", {}).get("message", "").split(chr(10))[0]
        if msg: info.commit_messages.append(msg)
    diff = gh_api(f"/repos/{owner}/{repo}/pulls/{num}", "application/vnd.github.v3.diff")
    info.diff = diff.decode("utf-8") if isinstance(diff, bytes) else str(diff)
    return info

def call_claude(prompt, system=""):
    key = os.environ.get("CLAUDE_API_KEY") or os.environ.get("ANTHROPIC_API_KEY")
    if not key:
        print("Error: set CLAUDE_API_KEY or ANTHROPIC_API_KEY", file=sys.stderr)
        sys.exit(1)
    body = json.dumps({
        "model": "claude-sonnet-4-20250514",
        "max_tokens": 4096,
        "temperature": 0.3,
        "system": system or "You are a senior code reviewer.",
        "messages": [{"role": "user", "content": prompt}]
    }).encode()
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=body,
        headers={
            "Content-Type": "application/json",
            "x-api-key": key,
            "anthropic-version": "2023-06-01",
        }
    )
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.loads(r.read())["content"][0]["text"]

def build_prompt(info):
    nl = chr(10)
    commits = nl.join(f"  - {m}" for m in info.commit_messages)
    diff = info.diff[:50000]
    return nl.join([
        f"# PR Review: {info.owner}/{info.repo}#{info.number}",
        "## Metadata",
        f"- Title: {info.title}",
        f"- Author: @{info.author}",
        f"- Files: {info.changed_files} (+{info.additions}/-{info.deletions})",
        f"- Commits:",
        commits,
        "## Description",
        info.description,
        "## Diff",
        f"```diff{nl}{diff}{nl}```",
        "## Review Instructions",
        "Analyze this PR and provide:",
        "1. Summary (2-3 sentences)",
        "2. Risks (bullet list)",
        "3. Suggestions (with code if applicable)",
        "4. Confidence: High/Medium/Low",
    ])

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--pr", required=True)
    p.add_argument("--output", "-o")
    p.add_argument("--basic", action="store_true")
    args = p.parse_args()
    owner, repo, num = parse_pr_url(args.pr)
    print(f"Fetching {owner}/{repo}#{num}...", file=sys.stderr)
    info = fetch_pr(owner, repo, num)
    print(f"{info.title}", file=sys.stderr)
    if args.basic:
        analysis = "## Summary\nBasic analysis.\n## Confidence\nLow - set CLAUDE_API_KEY."
    else:
        analysis = call_claude(build_prompt(info), "Senior code reviewer. Be direct.")
    nl = chr(10)
    review = nl.join([
        f"# PR Review: {info.owner}/{info.repo}#{info.number}",
        f"> **{info.title}** by @{info.author}",
        f"> {info.changed_files} files | +{info.additions}/-{info.deletions}",
        "---",
        analysis,
        "---",
        "*Generated by claude-review*"
    ])
    if args.output:
        with open(args.output, "w") as f: f.write(review)
        print(f"Written to {args.output}", file=sys.stderr)
    else:
        print(review)

if __name__ == "__main__":
    main()
